### ISSUE TITLE
Mixed content warnings

### ISSUE THREAD

**Issue by simonwex** [mozilla/hivelearningnetworks.org#34]
![image](https://cloud.githubusercontent.com/assets/25260/7434232/0e95b8fc-efee-11e4-9780-4d38d8230406.png)

**Comment by jbuck** [comment]
I'm not seeing any mixed content errors on the site https://www.dropbox.com/s/wemlokqovq1st1m/Screenshot%202015-05-04%2013.47.30.png?dl=0

**Comment by mmmavis** [comment]
It seems to be intermittent.  Could it be related to the WP configs?

**Comment by jbuck** [comment]
Hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha

okay this was driving me bonkers. STR:

1) Visit http://hivelearningnetworks.org
2) Visit https://hivelearningnetworks.org
3) :sob: 

Why are you crying on step 3, you may ask? Well, that's because the http version of the site with http resources was cached somewhere within the server, and then you visit the https version and it happily serves you up the http version of the site for a period of time until the cache busts.

**Comment by simonwex** [comment]
Thanks! This has been killing me, too!

**Comment by jbuck** [comment]
Okay, so it looks like there is a varnish process doing caching between the ELB and the nginx/fastcgi process running. @jdotpz what's the best way to get this working?

**Comment by jdotpz** [comment]
Down with http, https forever!
Don't allow http connections, redirect in the nginx conf before it ever populates varnish.

**Comment by jbuck** [comment]
Done, and I added HSTS for good measure.

**Comment by mmmavis** [comment]
( I don't quite understand what you guys were talking about ^ ) but yea thanks guys for fixing this

Yayyyyyyyyy, another WP issue solved! :sweat_smile:
